name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # See https://nodejs.org/en/about/releases/
                node-version: [16.x, 18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use NodeJS ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install, lint, test and generate coverage report
              run: |
                  npm install
                  npm run lint
                  npm run compile
                  npm run test:coverage
